### ISSUE TITLE
java.lang.IllegalStateException in doParse

### ISSUE THREAD

**Issue by lpar** [docopt/docopt.java#2]
The following help text:

```
Bug

Usage:
  bug [options] <command> ...
  bug (-h | --help)

Commands:
  show         Demonstrate bug

Options:
  -h --help    Show this help.
```

causes a crash at run time:

```
Exception in thread "main" java.lang.IllegalStateException
    at java.util.ArrayList$Itr.remove(ArrayList.java:849)
    at org.docopt.Docopt.doParse(Docopt.java:708)
    at org.docopt.Docopt.parse(Docopt.java:747)
    at org.docopt.Docopt.parse(Docopt.java:777)
    at Bug.main(Bug.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Pull request with fix to follow in a few minutes...

**Comment by lpar** [comment]
See pull request https://github.com/docopt/docopt.java/pull/3 for the (rather trivial) fix. The two commits are because I didn't realize you used tabs in the source until it was too late.
